name: CI
on:
  push:
    branches:
      - BE/master
    paths-ignore:
      - "**.md"
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run prebuild:prod
      - run: npm run build:prod
      - run: git config --config user.name "${{ env.GITHUB_ACTOR }}"
      - run: git config --config user.email "ci+etherio97@users.noreply.github.com"
