name: CI
on:
  push:
    branches:
      - BE/master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npx -p @nestjs/cli nest build
      - run: |
          git config --global user.name "ci"
          git config --global user.email "ci@users.noreply.github.com"
          git checkout --orphan main
          git add -f dist
          git commit -m "initial commit"
          git push -f origin main
